In [1]:
# importing packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
# importing data
spam_df = pd.read_csv('spam.csv')
spam_df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
spam_df.groupby(by = 'Category').describe()

Message                                                               
           count unique                                                top freq
Category                                                                       
ham         4825   4516                             Sorry, I'll call later   30
spam         747    641  Please call our customer service representativ...    4

In [12]:
spam_df['spam'] = spam_df['Category'].apply(lambda x : 0 if x =='ham' else  1)

In [13]:
spam_df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [31]:
X_train,X_test,y_train,y_test = train_test_split(spam_df['Message'],spam_df['spam'],test_size=0.25)

In [32]:
cv = CountVectorizer()

In [33]:
X_train_count = cv.fit_transform(X_train)

In [43]:
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [42]:
X_train_count.toarray().shape

(4179, 7369)

In [35]:
#pre-test

email = ["hello dude come for the game tonight"]
email_count = cv.transform(email)

In [36]:
model = MultinomialNB()

In [37]:
model.fit(X_train_count,y_train)

MultinomialNB()

In [38]:
model.predict(email_count)

array([0])

In [39]:
X_test_count= cv.transform(X_test)

In [40]:
model.predict(X_test_count)

array([0, 0, 0, ..., 0, 0, 1])

In [41]:
model.score(X_test_count,y_test)

0.9892318736539842

In [44]:
import joblib

joblib.dump(model,'spam_classifier.pkl')
joblib.dump(cv,'vectorizer.pkl')

['vectorizer.pkl']